const state={step:0,visited:new Set(),profileAnswers:{},postAnswers:{},reflection:'',ended:false,research:false,largeText:false,dyslexia:false,audio:true,reducedMotion:false};
const stage=document.getElementById('stage'),continueBtn=document.getElementById('continueBtn'),backBtn=document.getElementById('backBtn'),sceneHint=document.getElementById('sceneHint'),journalPanel=document.getElementById('journalPanel'),journalContent=document.getElementById('journalContent'),scrim=document.getElementById('scrim');

const profileItems=[
 {dimension:'Guidance',q:'A squire learns best when a master…',a:['names the road clearly','sets a direction, then watches','lets experience reveal the path','steps in only after failure','expects the worthy to find their own way'],scores:[5,4,3,2,1]},
 {dimension:'Succession',q:'A knight’s first duty to a gifted squire is to…',a:['prepare them to stand alone','keep them close until fully proven','protect the household from disruption','make use of their strongest talents','let ambition reveal itself over time'],scores:[5,3,2,1,2]},
 {dimension:'Recognition',q:'When a young squire begins to attract praise, a wise master should…',a:['create a harder test','share the attention','keep praise from becoming pride','remind them who opened the door','wait to see whether admiration lasts'],scores:[3,5,2,1,2]},
 {dimension:'Opportunity',q:'If another order offers a squire a rare opportunity, the master should…',a:['encourage the move','ask what the squire wants','delay until the household is stable','refuse if the squire is indispensable','decide what best serves the realm'],scores:[5,5,2,1,3]},
 {dimension:'Legacy',q:'Which saying sounds most like you?',a:['A legacy is measured by those who surpass us.','Guidance should be earned, not expected.','The realm comes before one person’s future.','A strong squire needs little encouragement.','The finest teachers are often silent.'],scores:[5,1,2,1,2]}
];
const places=[
 ['library','Library','Brother Aldren shows you three contradictory codes of advancement. Only your mentor can tell you which one governs your apprenticeship.','Study the codes'],
 ['forge','Forge','Rowan explains that a blade improves through specific correction, not vague approval.','Ask Rowan'],
 ['yard','Training Yard','Cedric already has written milestones and weekly coaching.','Observe training'],
 ['stables','Stables','The stable master says celebrated knights often keep capable squires close because competence is convenient.','Listen quietly'],
 ['garden','Rose Garden','Lady Elowen asks what future Sir Garrick has promised. You realize he has promised none.','Walk with Elowen'],
 ['chapel','Old Chapel','A scratched crest points toward a loose stone in the library wall.','Inspect the crest']
];
const expertReflection='A mentor does not owe an apprentice an immediate promotion. They do owe them an honest path: what readiness requires, what progress looks like, and what comes next. Direction communicates that the apprentice has a future worth preparing for.';
const expertQuote='A future stays believable when someone is willing to name the road toward it.';

function escapeHtml(str=''){return str.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(text){const t=document.createElement('div');t.className='toast';t.textContent=text;document.getElementById('toastRegion').appendChild(t);setTimeout(()=>t.remove(),2400)}
function setNav({next='Continue →',back=true,disabled=false,hint=''}){continueBtn.textContent=next;continueBtn.disabled=disabled;backBtn.disabled=!back;sceneHint.textContent=hint}
function person(asset,name,role,copy){return `<div class="character-card"><img class="portrait-art" src="assets/${asset}.svg" alt="Ink sketch of ${name}"><div><h3>${name}</h3><span class="badge">${role}</span><p>${copy}</p></div></div>`}
function answeredCount(obj){return Object.keys(obj).length}
function scoreAnswer(item,index){return item.scores[Number(index)-1]||0}
function scoresFor(answers){return profileItems.map((item,i)=>({dimension:item.dimension,score:scoreAnswer(item,answers[`q${i}`])}))}
function renderProfile(answers,prefix){return profileItems.map((item,i)=>`<fieldset class="prompt-card"><legend>${item.q}</legend><div class="scale">${item.a.map((text,n)=>`<label><input type="radio" name="${prefix}q${i}" data-key="q${i}" value="${n+1}" ${answers[`q${i}`]===n+1?'checked':''}><span>${text}</span></label>`).join('')}</div></fieldset>`).join('')}
function seals(score,kind=''){return `<span class="seal-scale ${kind}" aria-label="${score} of 5">${[1,2,3,4,5].map(n=>`<i class="${n<=score?'filled':''}"></i>`).join('')}</span>`}
function guidanceFor(dimension,score,delta){const low={Guidance:'Name expectations, milestones, and next steps instead of treating uncertainty as a test.',Succession:'Measure leadership by how well others can eventually succeed without you.',Recognition:'Share credit and visibility when an apprentice earns them.',Opportunity:'Ask what the apprentice wants, then support appropriate movement even when losing them is inconvenient.',Legacy:'Treat developing a future leader as part of your legacy, not a threat to it.'};const steady={Guidance:'Translate broad encouragement into specific milestones and next steps.',Succession:'Create one concrete opportunity for someone to operate independently.',Recognition:'Pair praise with meaningful access and responsibility.',Opportunity:'Test this belief when supporting growth creates a real short-term cost.',Legacy:'Turn this belief into a visible mentoring habit.'};if(score<=2)return low[dimension];if(delta<=0)return steady[dimension];return 'This conviction strengthened. Protect it when doing so becomes inconvenient.'}
function resultRows(){const pre=scoresFor(state.profileAnswers),post=scoresFor(state.postAnswers);return pre.map((p,i)=>({...p,end:post[i].score,delta:post[i].score-p.score,aspire:5}))}
function renderChronicle(){const rows=resultRows(),avgPre=rows.reduce((s,r)=>s+r.score,0)/5,avgPost=rows.reduce((s,r)=>s+r.end,0)/5;return `<section class="scene page-turn"><div class="chronicle-cover"><div class="panel illustrated"><img class="scene-art" src="assets/investiture.svg" alt="Finished ink-and-wash illustration of Camelot at dusk"><div class="art-copy"><span class="eyebrow">Episode I complete</span><h1>The Chronicle of Your Apprenticeship</h1><p class="lede">The same code. A different understanding.</p><p class="copy">The Chronicler compares who you were when you entered Sir Garrick’s service, who you are today, and the knight you have chosen to become.</p></div></div><div class="panel sketch"><span class="eyebrow">Your legacy so far</span><div class="legacy-strip"><div class="legacy-item"><span>Hope</span><div class="legacy-meter"><i style="width:72%"></i></div></div><div class="legacy-item"><span>Honor</span><div class="legacy-meter"><i style="width:82%"></i></div></div><div class="legacy-item"><span>Legacy</span><div class="legacy-meter"><i style="width:${Math.round(avgPost*20)}%"></i></div></div></div><div class="quote">Every apprentice believes they seek a sword. Most are really searching for a mentor.</div></div></div><div class="panel sketch"><span class="eyebrow">The Knight’s Code</span><div class="code-grid">${rows.map(r=>`<article class="code-row"><strong>${r.dimension}</strong><div><span class="small-note">At the beginning</span>${seals(r.score)}</div><div><span class="small-note">Today</span>${seals(r.end)}</div><div><span class="small-note">The knight you aspire to be</span>${seals(r.aspire,'aspire')}</div><p class="change-note">${guidanceFor(r.dimension,r.end,r.delta)}</p></article>`).join('')}</div><div class="research-panel"><span class="research-badge">Research mode</span><h3>Assessment details</h3><table class="raw-score-table"><thead><tr><th>Dimension</th><th>Baseline</th><th>Post</th><th>Change</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.dimension}</td><td>${r.score}</td><td>${r.end}</td><td>${r.delta>0?'+':''}${r.delta}</td></tr>`).join('')}</tbody></table><p>Overall mean: ${avgPre.toFixed(1)} → ${avgPost.toFixed(1)}. This is descriptive feedback for prototype playtesting, not a validated diagnostic.</p></div></div></section>`}
function renderMemory(){const rows=resultRows();const strongest=[...rows].sort((a,b)=>b.delta-a.delta)[0];const focus=[...rows].sort((a,b)=>(a.end-b.end)||(a.delta-b.delta))[0];return `<section class="scene page-turn"><div class="memory-spread"><article class="memory-page"><span class="eyebrow">Trial of Direction</span><h2>What happened</h2><img class="scene-art" src="assets/garrick-cedric.svg" alt="Sir Garrick giving Cedric a detailed training plan while the player watches from an archway"><p class="copy">Sir Garrick withheld the path from you, then gave it freely to another squire.</p><h2>What I learned</h2><p class="hand">${escapeHtml(state.reflection)}</p></article><article class="memory-page"><span class="eyebrow">Words of the Wise</span><p class="copy">${expertReflection}</p><div class="quote">${expertQuote}</div><h2>My oath</h2><p class="hand">I will make the road visible, even when the destination is not immediate.</p><p class="small-note">A carved wooden shield from the stable page has been pressed into the binding.</p></article></div><div class="panel sketch chronicle-mini"><span class="eyebrow">The Knight’s Code, revisited</span><h2>How your thinking changed</h2><div class="memory-code-grid">${rows.map(r=>`<div class="memory-code-row"><strong>${r.dimension}</strong><span><small>Beginning</small>${seals(r.score)}</span><span><small>Today</small>${seals(r.end)}</span><span class="${r.delta>0?'delta-up':r.delta<0?'delta-down':'delta-flat'}">${r.delta>0?'+':''}${r.delta}</span></div>`).join('')}</div><div class="shift-summary"><div class="shift-card"><strong>Greatest shift</strong><p>${strongest.dimension}: ${strongest.delta>0?`your conviction strengthened by ${strongest.delta}.`:'your view held steady.'}</p></div><div class="shift-card"><strong>Next trial will test</strong><p>${focus.dimension}: ${guidanceFor(focus.dimension,focus.end,focus.delta)}</p></div></div></div><div class="panel sketch"><span class="eyebrow">The next page</span><h2>Trial II: Courage</h2><p class="copy">A sealed tournament invitation is visible beneath Sir Garrick’s desk blotter. Your name is written on it.</p><div class="quote">Episode II asks whether a mentor creates opportunities, or merely promises that one will arrive someday.</div></div></section>`}

const scenes=[
()=>{setNav({next:'Begin →',back:false,hint:'Open the journal and enter the story.'});return `<section class="scene opening-scene page-turn"><article class="reference-cover"><img src="assets/ref-title.png" alt="Illuminated manuscript cover for A Tale of Two Knights"><button id="heroJournalBtn" class="reference-journal-button" type="button">Open Journal</button></article><aside class="opening-cast manuscript-panel"><span class="ribbon-label">Episode I Cast</span>${person('garrick','Sir Garrick','Legendary knight','Charming, celebrated, and always certain the room is watching.')}${person('elowen','Lady Elowen','Noble envoy','Quietly perceptive. Rarely impressed by polished armor.')}${person('pip','Pip','Questionable fox spirit','Small, observant, and innocent of several unproven thefts.')}</aside></section>`},
()=>{setNav({next:'Present your answers →',disabled:answeredCount(state.profileAnswers)<5,hint:answeredCount(state.profileAnswers)<5?'Choose one instinctive response for each prompt.':'Sir Garrick has finished taking notes.'});return `<section class="scene page-turn"><div class="panel sketch"><div class="profile-intro"><div><span class="eyebrow">Sir Garrick’s apprentice profile</span><h2>“Before I train you, I should know what sort of squire has entered my service.”</h2><p class="copy">Choose the answer nearest your instinct. There are no noble answers here, only revealing ones.</p></div><div class="garrick-note">“Do not choose what sounds admirable. Choose what sounds true.”<br>— Sir Garrick</div></div>${renderProfile(state.profileAnswers,'pre')}<p class="seal-mark">Your choices are sealed into the journal.</p></div></section>`},
()=>{setNav({next:'Enter the keep →',hint:'Choose your first route into the apprenticeship.'});return `<section class="scene two-col page-turn"><div class="panel illustrated"><img class="scene-art" src="assets/keep-panorama.svg" alt="Illustrated map of the Royal Keep"><div class="art-copy"><span class="eyebrow">The Royal Keep</span><h2>Three doors. One first impression.</h2><p class="copy">Sir Garrick has vanished into court. Where will you begin?</p><div class="choice-grid"><button class="choice-button route" data-route="yard">Training Yard: prove yourself</button><button class="choice-button route" data-route="library">Library: learn the old codes</button><button class="choice-button route" data-route="garden">Rose Garden: seek Lady Elowen</button></div></div></div><div class="panel">${person('aldren','Brother Aldren','Keeper of records','Remembers every knightly code and where he misplaced his spectacles.')}${person('rowan','Rowan','Blacksmith apprentice','Believes skill improves through precise feedback and scorched eyebrows.')}</div></section>`},
()=>{setNav({next:'Compare what you found →',disabled:state.visited.size<3,hint:state.visited.size<3?`Visit ${3-state.visited.size} more location${3-state.visited.size===1?'':'s'} to continue.`:'Three paths now point toward the same missing answer.'});return renderExploration()},
()=>{setNav({next:'Follow Pip’s clue →',hint:'The oldest lesson in the keep has been waiting a very long time.'});return `<section class="scene two-col page-turn"><div class="panel illustrated"><img class="scene-art" src="assets/library.svg" alt="Finished sketch of an old library with a loose stone and hidden journal"><div class="art-copy"><span class="eyebrow">A page left behind</span><h2>“Perhaps next year.”</h2><p class="copy">Behind a loose stone, you find the final entry of a former squire.</p><div class="quote">“Sir Garrick says the path will become clearer next year. I must simply work harder.”</div><p class="small-note">Dated twenty years ago. No later entries.</p></div></div><div class="panel">${person('pip','Pip','Unlicensed investigator','“Either the path is very long… or the map keeps moving.”')}</div></section>`},
()=>{setNav({next:'Ask Sir Garrick again →',hint:'This time, you bring evidence and a direct question.'});return `<section class="scene two-col page-turn"><div class="panel">${person('garrick','Sir Garrick','Your mentor','Warm smile. Perfect posture. No answer yet.')}</div><div class="panel sketch"><h2>A reasonable question</h2><p class="copy">You explain what you found and ask for the milestones required for knighthood.</p><div class="quote">“You are eager. Admirable. Dangerous, if poorly timed.”</div><p class="copy">He promises to discuss it after the next ceremony.</p><p class="hand">Pip writes: “A date is not a plan.”</p></div></section>`},
()=>{setNav({next:'Watch from the archway →',hint:'The truth arrives disguised as someone else’s good fortune.'});return `<section class="scene page-turn"><div class="panel illustrated"><img class="scene-art" src="assets/garrick-cedric.svg" alt="Sir Garrick mentoring Cedric while the player watches unseen"><div class="art-copy"><span class="eyebrow">The unforgettable moment</span><h2>He knows exactly how to mentor</h2><p class="copy">From the archway, you overhear Sir Garrick giving Cedric a detailed plan: five milestones, weekly coaching, a tournament introduction, and the knight who will sponsor him.</p><div class="quote">“A good squire should never wonder what comes next.”</div><p class="hand">He has a map. He simply chose not to give it to you.</p></div></div></section>`},
()=>{setNav({next:'Go to the campfire →',hint:'Pip has already stolen the marshmallows. No one knows from where.'});return `<section class="scene two-col page-turn"><div class="panel illustrated"><img class="scene-art" src="assets/campfire.svg" alt="Lady Elowen and the player beside a campfire beneath Camelot"><div class="art-copy"><h2>Campfire</h2><p class="copy">Lady Elowen notices you watching the flames instead of eating.</p><div class="quote">“Silence can be an answer. It is simply rarely the answer we hoped for.”</div></div></div><div class="panel">${person('elowen','Lady Elowen','Unexpected ally','She does not tell you what to think. She asks what the silence cost you.')}</div></section>`},
()=>{setNav({next:'Open Words of the Wise →',disabled:!state.reflection,hint:state.reflection?'Your thought has been sealed into the journal.':'Write and seal one honest thought to continue.'});return `<section class="scene page-turn"><div class="panel sketch"><span class="eyebrow">Campfire journal</span><h2>What did Sir Garrick’s silence make you believe about your future?</h2><textarea id="reflectionInput" placeholder="I began to wonder whether…">${escapeHtml(state.reflection)}</textarea><button id="saveReflection" class="secondary-button">Seal this thought in the journal</button></div></section>`},
()=>{setNav({next:'Write the oath you will keep →',hint:'Compare your insight with the guidance of an experienced mentor.'});return `<section class="scene two-col page-turn"><div class="panel sketch"><span class="eyebrow">Your journal</span><p class="hand">${escapeHtml(state.reflection)}</p></div><div class="panel"><span class="eyebrow">Words of the Wise</span><h2>Direction is a form of investment</h2><p class="copy">${expertReflection}</p><div class="quote">${expertQuote}</div></div></section>`},
()=>{setNav({next:'Read the Code again →',hint:'This promise becomes the first line of your own Knight’s Oath.'});return `<section class="scene two-col page-turn"><div class="panel sketch"><span class="eyebrow">The oath I will keep</span><h2>Sir Garrick today</h2><p class="copy">He withheld the path while giving it freely to someone else.</p><h2>The knight I will become</h2><div class="quote">I will make the road visible, even when the destination is not immediate.</div><p class="copy">A stable page quietly places a carved wooden shield beside your journal.</p><p class="hand">“You are the first person who explained something to me without making me feel foolish.”</p></div><div class="panel illustrated"><img class="scene-art" src="assets/journal-memory.svg" alt="Finished illustration of the campaign journal with a carved shield and pressed flower"><div class="art-copy"><p class="copy">The journal remembers what the castle would prefer to forget.</p></div></div></section>`},
()=>{setNav({next:'Reveal the Chronicle →',disabled:answeredCount(state.postAnswers)<5,hint:answeredCount(state.postAnswers)<5?'Read each principle again from where you stand now.':'The second reading is complete.'});return `<section class="scene page-turn"><div class="panel sketch"><div class="profile-intro"><div><span class="eyebrow">The Knight’s Code: second reading</span><h2>“It is curious how the same words change after one has lived inside them.”</h2><p class="copy">Choose the answer nearest your belief now. Your first answers remain sealed.</p></div><div class="garrick-note">The same questions.<br>A different vantage point.</div></div>${renderProfile(state.postAnswers,'post')}<p class="seal-mark">Your second reading will be compared with the first.</p></div></section>`},
()=>{setNav({next:'Turn to the memory page →',hint:'The Chronicle records what strengthened and what remains unfinished.'});return renderChronicle()},
()=>{state.ended=true;setNav({next:'Return to the beginning ↺',hint:'Episode I is preserved in your journal. Episode II waits beneath a sealed letter.'});return renderMemory()}
];

function renderExploration(){return `<section class="scene page-turn"><div class="panel sketch wide"><span class="eyebrow">Explore the keep</span><h2>Find the path to knighthood</h2><p class="copy">Visit any three locations. Curiosity is never punished.</p><div class="quest-map">${places.map(([id,name,text,action])=>`<article class="location ${state.visited.has(id)?'visited':''}"><img class="location-art" src="assets/${id}.svg" alt="Ink sketch of the ${name}"><div class="location-copy"><h3>${name}</h3><span class="location-state">${state.visited.has(id)?'Journal updated':'Unexplored'}</span><p>${state.visited.has(id)?text:'An unanswered question waits here.'}</p></div><button class="secondary-button visit-btn" data-place="${id}">${state.visited.has(id)?'Read again':action}</button></article>`).join('')}</div></div></section>`}
function bindScene(){const heroJournal=document.getElementById('heroJournalBtn');if(heroJournal)heroJournal.addEventListener('click',openJournal);document.querySelectorAll('.route').forEach(btn=>btn.addEventListener('click',()=>{state.visited.add(btn.dataset.route);toast('First path recorded in the journal');state.step=3;render()}));document.querySelectorAll('.visit-btn').forEach(btn=>btn.addEventListener('click',()=>{state.visited.add(btn.dataset.place);toast('Journal updated');render()}));document.querySelectorAll('input[type=radio]').forEach(input=>input.addEventListener('change',e=>{const target=e.target.name.startsWith('post')?state.postAnswers:state.profileAnswers;target[e.target.dataset.key]=Number(e.target.value);render()}));const save=document.getElementById('saveReflection');if(save)save.addEventListener('click',()=>{const val=document.getElementById('reflectionInput').value.trim();if(val.length<8){toast('Write one complete thought.');return}state.reflection=val;toast('Journal updated');render()})}
function render(){document.body.classList.toggle('research-on',state.research);document.body.classList.toggle('large-text',state.largeText);document.body.classList.toggle('dyslexia-mode',state.dyslexia);document.body.classList.toggle('reduce-motion',state.reducedMotion);stage.innerHTML=scenes[state.step]();bindScene();updateJournal();requestAnimationFrame(()=>stage.focus())}
function canContinue(){if(state.step===1)return answeredCount(state.profileAnswers)===5;if(state.step===3)return state.visited.size>=3;if(state.step===8)return !!state.reflection;if(state.step===11)return answeredCount(state.postAnswers)===5;return true}
function playSound(kind='page'){if(!state.audio)return;try{const A=window.AudioContext||window.webkitAudioContext;const c=new A();const o=c.createOscillator(),g=c.createGain();o.type=kind==='seal'?'triangle':'sine';o.frequency.value=kind==='seal'?180:320;g.gain.setValueAtTime(.0001,c.currentTime);g.gain.exponentialRampToValueAtTime(.055,c.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.11);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch(e){}}
continueBtn.addEventListener('click',()=>{if(!canContinue())return;playSound('page');if(state.ended){location.reload();return}state.step=Math.min(scenes.length-1,state.step+1);render()});backBtn.addEventListener('click',()=>{if(state.step===0)return;playSound('page');state.step=Math.max(0,state.step-1);render()});
const settingsPanel=document.getElementById('settingsPanel'),settingsBtn=document.getElementById('settingsBtn');function openSettings(){settingsPanel.classList.add('open');settingsPanel.setAttribute('aria-hidden','false');settingsBtn.setAttribute('aria-expanded','true');scrim.hidden=false;document.getElementById('closeSettingsBtn').focus()}function closeSettings(){settingsPanel.classList.remove('open');settingsPanel.setAttribute('aria-hidden','true');settingsBtn.setAttribute('aria-expanded','false');if(!journalPanel.classList.contains('open'))scrim.hidden=true;settingsBtn.focus()}settingsBtn.addEventListener('click',openSettings);document.getElementById('closeSettingsBtn').addEventListener('click',closeSettings);document.getElementById('researchMode').addEventListener('change',e=>{state.research=e.target.checked;render()});document.getElementById('largeText').addEventListener('change',e=>{state.largeText=e.target.checked;render()});document.getElementById('dyslexiaMode').addEventListener('change',e=>{state.dyslexia=e.target.checked;render()});document.getElementById('audioMode').addEventListener('change',e=>{state.audio=e.target.checked;playSound('seal')});document.getElementById('motionMode').addEventListener('change',e=>{state.reducedMotion=e.target.checked;render()});document.getElementById('journalBtn').addEventListener('click',openJournal);document.getElementById('closeJournalBtn').addEventListener('click',closeJournal);scrim.addEventListener('click',()=>{if(journalPanel.classList.contains('open'))closeJournal();if(settingsPanel.classList.contains('open'))closeSettings()});document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');updateJournal(tab.dataset.tab)}));
function openJournal(){journalPanel.classList.add('open');journalPanel.setAttribute('aria-hidden','false');scrim.hidden=false;updateJournal();document.getElementById('closeJournalBtn').focus()}
function closeJournal(){journalPanel.classList.remove('open');journalPanel.setAttribute('aria-hidden','true');scrim.hidden=true;document.getElementById('journalBtn').focus()}
function updateJournal(tab=document.querySelector('.tab.active')?.dataset.tab||'quest'){const content={quest:`<h3>Trial of Direction</h3><p><strong>Goal:</strong> Learn what the path to knighthood requires.</p><p><strong>Places explored:</strong> ${state.visited.size}/3 required.</p><p><strong>Royal Investiture:</strong> Five days remain.</p>`,people:`<h3>People</h3><p><strong>Sir Garrick:</strong> celebrated, charming, and increasingly selective with his guidance.</p><p><strong>Lady Elowen:</strong> notices what others excuse.</p><p><strong>Pip:</strong> unreliable about ownership, reliable about hypocrisy.</p><p><strong>Rowan:</strong> believes skill should be developed, not merely used.</p><p><strong>Cedric:</strong> rival squire with a real development plan.</p>`,evidence:`<h3>Clues</h3>${state.step>=4?'<p>• A former squire waited twenty years for “next year.”</p>':'<p>No clues collected yet.</p>'}${state.step>=6?'<p>• Sir Garrick gave Cedric the exact guidance he withheld from you.</p>':''}`,code:`<h3>Your Oath</h3><p>First reading sealed: ${answeredCount(state.profileAnswers)}/5</p><p>Second reading sealed: ${answeredCount(state.postAnswers)}/5</p>${state.reflection?`<h3>Campfire thought</h3><p class="hand">${escapeHtml(state.reflection)}</p>`:''}${state.step>=10?'<div class="quote">I will make the road visible, even when the destination is not immediate.</div>':''}`,memory:state.step>=13?`<h3>Episode Memory</h3><p><strong>What happened:</strong> Sir Garrick withheld the path while giving it freely to Cedric.</p><p><strong>What I learned:</strong></p><p class="hand">${escapeHtml(state.reflection)}</p><div class="quote">${expertQuote}</div><h3>The Knight’s Code, revisited</h3>${resultRows().map(r=>`<p><strong>${r.dimension}:</strong> ${r.score} → ${r.end} (${r.delta>0?'+':''}${r.delta})</p>`).join('')}`:'<h3>Episode Memory</h3><p>This page will be written when the Trial is complete.</p>'};journalContent.innerHTML=content[tab]}
render();
